manifest:
  self:
    path: zephyr-honeygui

  remotes:
    - name: rtkconnectivity
      url-base: https://github.com/rtkconnectivity
    - name: realmcu
      url-base: https://github.com/realmcu

  projects:
    - name: zephyr
      remote: rtkconnectivity
      revision: realtek-main-v3.5.0
      import:
        name-allowlist:
          - cmsis
          - hal_realtek
          - tinycrypt
          - mbedtls
    - name: honeygui
      remote: realmcu
      repo-path: HoneyGUI
      path: modules/lib/gui/honeygui
    - name: wearable
      remote: realmcu
      repo-path: Wearable
      path: modules/lib/gui/wearable
    - name: rtk-display-driver
      remote: realmcu
      repo-path: Wearable
      path: modules/lib/gui/rtk-driver