manifest:
  self:
    path: zephyr-honeygui

  remotes:
    - name: rtkconnectivity
      url-base: https://github.com/rtkconnectivity
    - name: display
      url-base: ssh://cn4soc.rtkbf.com:29418

  projects:
    - name: zephyr
      remote: rtkconnectivity
      revision: realtek-main-v3.5.0
      import:
        name-allowlist:
          - cmsis
          - hal_realtek
          - tinycrypt
          - mbedtls
    - name: honeygui
      remote: display
      repo-path: HoneyGUI
      path: modules/display/honeygui
    - name: wearable
      remote: display
      repo-path: Wearable
      path: modules/display/wearable
    - name: rtk-display-driver
      remote: display
      repo-path: HoneyRepo/driver/display
      path: modules/display/rtk-driver