manifest:
  self:
    path: zephyr-honeygui

  remotes:
    - name: rtkconnectivity
      url-base: https://github.com/rtkconnectivity

  projects:
    - name: zephyr
      remote: rtkconnectivity
      revision: realtek-main-v3.5.0
      import:
        name-allowlist:
          - cmsis
          - hal_realtek
          - tinycrypt
          - mbedtls